contact_links:
  - name: Предложение
    url: https://discord.gg/astroplex
    about: Свои предложения можете оставлять в соответствующем канале Discord.
  - name: Сообщить об уязвимости
    url: https://discord.gg/astroplex
    about: Пожалуйста, сообщайте о серьезных эксплойтах и уязвимостях безопасности сайленту в Discord.
